In [1]:
list = [1,2,3,4,5,6,7,8,9,10]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [2]:
list[1:3]

[2, 3]

In [3]:
list[:-1]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list[::-1]

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [5]:
dict = {1:'Ram', 2:'Shyam'}
dict

{1: 'Ram', 2: 'Shyam'}

In [6]:
dict[3] = 'Hira'
dict

{1: 'Ram', 2: 'Shyam', 3: 'Hira'}

In [7]:
for key, value in dict.items():
    print(key, value)

1 Ram
2 Shyam
3 Hira


In [8]:
def function():
    print("No arg here")
    
function()

def function2(arg1):
    print(arg1)
    
function2("arg here")

No arg here
arg here


In [9]:
ints = int(input("Enter a number n\t"))

if ints % 2 == 0:
    print(f"{ints} is even.")
else:
    print(f"{ints} is odd.")

Enter a number n	 3


3 is odd.


In [10]:
print(f"Square of {ints} is {ints ** 2}")

Square of 3 is 9


In [11]:
2 < 1

False

In [12]:
class class1():
    def __init__(self):
        self.id = 1
        self.name = "John"
        
    def show(self):
        name1 = self.name # initializing name 
        # print(f"Name: {self.name} ID: {self.id}")
        print(f"Name: {name1} ID: {self.id}")
        

obj1 = class1()
obj1.show(), obj1.id, obj1.name


Name: John ID: 1


(None, 1, 'John')

In [13]:
# inheritance
class class2(class1):
        
    def show2(self):
        self.show()    

In [14]:
obj2 = class2()
obj2.show()

Name: John ID: 1


In [15]:
from evenodd import even_odd

In [16]:
even_odd(2)

Even


In [17]:
import numpy as np

In [18]:
np.__version__

'1.16.2'

In [19]:
l1 = [1,2,3,4,5]
print(type(l1))
arr = np.array(l1)
print(type(arr))
arr  #can be sliced

<class 'list'>
<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [20]:
zeros = np.zeros([5,5])

In [21]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
zeros.shape

(5, 5)

In [23]:
zeros.reshape(25,1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [24]:
zeros.reshape(1,25)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
zeros.reshape(25,)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
zeros ,zeros.reshape(-1,  25) #rows any arbitrary number but 25 column compulsory

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]]))

In [27]:
repeat = np.repeat(10, 100)
repeat

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [28]:
repeat.reshape(10,10)

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [29]:
repeat1 = np.repeat(10, 100).reshape(10,10)
sums = np.sum(repeat1, axis=1)
sums

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [30]:
mean = np.mean(repeat)
mean

10.0

In [31]:
l2 = [1,2,3]
arr = np.array(l2)
#l2 ** 2 #not possible to square in list
arr ** 2 #square is possible in array

array([1, 4, 9], dtype=int32)

In [32]:
np.pi

3.141592653589793

In [33]:
random = np.random.randn(2,5)  # gives random values in a matrix of 2x5.
                            # Increase parameter for higher dimension --> random.randn(2,5,1,...)
random

array([[ 1.21680369, -1.74867214, -0.4861237 ,  0.69001865,  0.05619873],
       [-0.57272056,  1.12421778, -1.82491708,  0.7887716 ,  0.50323601]])

In [34]:
n = np.random.randint(1,100,100) # size can be given in matrix, i.e. (1,2) or simply 1 dimension
n

array([28, 37, 39, 60, 24, 89, 71, 20, 61, 67, 28, 37, 73, 45, 55, 19, 15,
       96, 14, 75, 33, 59, 55,  3, 26, 40,  5, 76, 46, 75, 32, 82, 25, 70,
        4, 43, 18, 29, 71, 31, 52, 30, 34, 39,  3, 34, 22, 27, 91, 21, 24,
       98,  4, 46, 91, 47, 66, 93, 61, 93, 82,  2, 47, 37, 78, 51, 50, 54,
       63, 16, 17, 47, 12,  3,  5,  6, 69, 64, 18, 88, 86, 32, 10, 54, 58,
       89, 36, 50, 15, 57, 77, 40, 91,  4, 71, 50, 32, 85, 35, 76])

In [35]:
from collections import Counter

In [36]:
counts = Counter(n)
type(counts)

collections.Counter

In [37]:
dict(counts), counts

TypeError: 'dict' object is not callable

In [ ]:
## tuple cannot be altered. It is necessary to create tuple beforehand of operation.
## pop can be used in list but not in array.

In [47]:
#dict
d1 = {}
d1[1] = "NEPAL"
d1[2] = "USA"
d1

{1: 'NEPAL', 2: 'USA'}

In [48]:
d1.keys()

dict_keys([1, 2])

In [49]:
d1.values()

dict_values(['NEPAL', 'USA'])

In [43]:
#array
l1 = [1,2,3,4]
arr = np.array(l1, dtype = np.float)
arr

array([1., 2., 3., 4.])

In [44]:
arr[1] = 0
arr

array([1., 0., 3., 4.])

In [1]:
from evenodd import even_odd

even_odd(4)

Even
